from pathlib import Path
import hashlib,json,re,subprocess
R=Path('/home/azureuser/nova-community-agent');O=R/'evidence/agent-review-2'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def counts(text):return {k:int(v) for k,v in re.findall(r'^[#ℹ] (tests|pass|fail|cancelled|skipped|todo) (\d+)$',text,re.M)}
results=[]
for name in ['test-results.json','supplemental-results.json']:
 for row in json.loads((O/name).read_text()):
  row['counts']=counts((O/row['log']).read_text());results.append(row)
extra=[('file-put-isolated',0,['node','--import','tsx','--test','--test-reporter=tap','--test-name-pattern=lease loss during actual file put','evidence/agent-review-2/supplemental.test.ts']),('supplemental-rerun',0,['node','--import','tsx','--test','--test-reporter=tap','--test-concurrency=1','evidence/agent-review-2/supplemental.test.ts']),('delayed-lease-error',1,['node','--import','tsx','--test','--test-reporter=tap','evidence/agent-review-2/delayed-lease-error.test.ts']),('delayed-lease-no-listener',1,['node','--import','tsx','--test','--test-reporter=tap','evidence/agent-review-2/delayed-lease-no-listener.test.ts'])]
for group,n in [('file-put-repeat',8),('supplemental-repeat',4)]:
 for i in range(1,n+1):extra.append((f'{group}-{i}',0,['node','--import','tsx','--test','--test-reporter=tap',*(['--test-name-pattern=lease loss during actual file put'] if group=='file-put-repeat' else ['--test-concurrency=1']),'evidence/agent-review-2/supplemental.test.ts']))
for label,code,cmd in extra:
 p=O/(label+'.log');results.append({'label':label,'exit_code':code,'command':cmd,'counts':counts(p.read_text()),'log':p.name,'log_sha256':sha(p)})
for row in results:row.setdefault('cwd',str(R))
(O/'execution-results.json').write_text(json.dumps(results,indent=2)+'\n')
before=json.loads((O/'source-hashes-before.json').read_text());changes=[p for p,h in before.items() if not (R/p).is_file() or sha(R/p)!=h]
fix=json.loads((R/'evidence/agent-fix-1/verification.json').read_text())
hashes={p:sha(R/p) for p in fix['candidateSha256']};assert hashes==fix['candidateSha256'];assert not changes
source_manifest={p:sha(R/p) for p in before if p.startswith(('src/','scripts/','tests/','migrations/','docs/')) or p in ['package.json','package-lock.json','tsconfig.json']}
source_digest=hashlib.sha256(json.dumps(source_manifest,sort_keys=True,separators=(',',':')).encode()).hexdigest()
(O/'reviewed-source-manifest.json').write_text(json.dumps({'hash_algorithm':'sha256','aggregate_encoding':'UTF-8 canonical JSON sorted keys, separators comma/colon of files object','aggregate_sha256':source_digest,'files':source_manifest},indent=2)+'\n')
verdict={
'passed':False,
'security_concerns':[],
'logic_errors':[{'id':'R2-LEASE-DELAYED-ERROR','reopens':'R1-LEASE-LOSS','severity':'medium','title':'Lease invalidation before its error event installs a pg-pool idle listener that can re-emit an unhandled pool error','locations':['src/runtime.ts:15-25','src/runtime.ts:43-49','node_modules/pg-pool/index.js:51-62','node_modules/pg-pool/index.js:384-397','scripts/config.ts:11-14'],'observed':'Supplemental real file-put handover intermittently failed with PG administrator-termination error. Exact reruns passed, so a deterministic event-order probe delayed actual dedicated-client error/end delivery until a protected request detected the missing pg_locks row. Runtime.check invalidated and release(true) attached pg-pool idleListener. Delivery of the already pending real PG error then emitted pool.error. With an observing pool listener, the leaked error was recorded; with no pool error listener (production configuration), the test threw the PG error. New HTTP work was already rejected with 503, but process availability remains unsafe.','expected':'Every supported dedicated-lease loss ordering must invalidate/fence without an unhandled pool error, including ownership-check invalidation before delayed client error/end. Retaining the Runtime error listener alone does not suppress pg-pool forwarding.','reproduction':['node --import tsx --test --test-reporter=tap evidence/agent-review-2/delayed-lease-error.test.ts','node --import tsx --test --test-reporter=tap evidence/agent-review-2/delayed-lease-no-listener.test.ts'],'evidence':['supplemental.log','delayed-lease-error.log','delayed-lease-error.json','delayed-lease-no-listener.log'],'scope_note':'Controlled event-delivery scheduling of real PG termination on private local DB; no production/client implementation edited. Does not demonstrate stale tool writes or double inference. Original ordinary lease-loss probe now passes.'}],
'suggestions':['Add this ownership-check-before-client-error ordering to the permanent runtime regression suite when fixing the remaining lease listener lifecycle issue. Do not weaken the corrected assertion to accept a pool error.'],
'summary':'NOT APPROVED: session rollback, generated-source rejection and exclusive startup are verified, but one reproducible dedicated-lease error-ordering availability regression remains. The unchanged local controlled-provider engine gate cannot close yet; no implementation edit or commit was made.',
'scope':'Local controlled-provider J1 engine only; private embedded PostgreSQL and loopback HTTP.',
'gate':{'state':'blocked','allow_ui_cv_on_pass':False,'reason':'R2-LEASE-DELAYED-ERROR remains unresolved; no blanket new-feature audit requested.'},
'closed_blockers':['R1-SESSION-WRITER','R1-PROVENANCE','R1-STARTUP-RESERVATION'],
'partially_fixed_blockers':['R1-LEASE-LOSS'],
'verified_behavior':['Final initiating-session authorization after canonical artifact, receipt and terminal writes rolls back mutation, revision, receipt, assistant message, task completion and outbox effects on expiry. Positive multi-tool and terminal controls pass.','Assistant messages rejected as user_supplied sources; user/file source foundation tests pass.','Exclusive runtime ownership precedes file initialization and destructive startup recovery in agent/non-agent/no-file modes. Pending reservation and upload survive refused overlap.','Shared handover barrier drains actual old artifact and file-put writes before recovery; old product writes roll back.','Ordinary lease error and end invalidate runtime; healthy DB persists unknown independently of a held file read; old/new runtime, cancel/purge and listener cleanup controls pass. Delayed error after ownership-check invalidation remains broken.'],
'execution_results':'execution-results.json',
'headline_tests':{'permanent_regressions':next(x['counts'] for x in results if x['label']=='permanent-regressions'),'original_unchanged_probes':next(x['counts'] for x in results if x['label']=='unchanged-original-probes'),'full_suite':next(x['counts'] for x in results if x['label']=='full-suite'),'typecheck_exit':0,'diff_check_exit':0,'baseline_original_expected_failures':next(x['counts'] for x in results if x['label']=='baseline-original-probes'),'baseline_final_write_expected_failures':next(x['counts'] for x in results if x['label']=='baseline-final-write-probes')},
'positive_controls':['controlled protocol: automatic tools revise canonical artifact, persist assistant, reopen and replay without inference','SIGKILL during real provider await survives PG and API restart as unknown; explicit new turn recovers','question pauses task; explicit answer resumes with file observation, scope checks and terminal receipt'],
'source':{'head':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip(),'state':'uncommitted candidate; HEAD alone is not candidate identity','candidate_sha256':hashes,'aggregate_sha256':source_digest,'full_manifest':'reviewed-source-manifest.json','matches_fix_verification':True},
'preservation':{'protected_files':len(before),'changed':changes,'original_current_probe_copies_byte_identical':all(sha(O/n)==sha(R/'evidence/agent-review-1'/n) for n in ['adversarial.test.ts','lease-loss.test.ts']),'baseline_probe_assertions_unchanged':True,'baseline_path_only_diffs':'baseline-probes/*.path-only.diff','review_writes_only':'evidence/agent-review-2/'},
'limits':['Not real-model inference, semantic prompt-injection resistance, UI/CV/voice, cloud identity/authorization, deployment or external providers. No metadata/cloud/credential discovery performed.','Per-database single-host singleton only; not cross-database shared-root locking or distributed scheduling.','Full database network partition not injected; persistence during unavailable DB remains best effort with restart fallback.','Prior committed effects remain durable; arbitrary indefinitely held DB/file work can delay drain/close.','Synthetic event-delivery ordering reproduces an actual intermittent local failure; repeated ordinary passes do not resolve the deterministic listener defect.'],
'environment':{'node':subprocess.check_output(['node','--version'],text=True).strip(),'python':subprocess.check_output(['python3','--version'],text=True).strip()}
}
(O/'verdict.json').write_text(json.dumps(verdict,indent=2)+'\n')
print(json.dumps({'passed':verdict['passed'],'headline_tests':verdict['headline_tests'],'source_aggregate_sha256':source_digest,'protected_files':len(before),'changes':changes},indent=2))
