'use strict';
const $=s=>document.querySelector(s);let workspace={conversations:[],artifacts:[],runs:[]},current=null,sequence=0,task=null,run=null,epoch=0,busy=false,artifact=null,revision=null,dirty=false,saving=false,artifactRequest=0,timer,noticeTimer;
const invite=new URLSearchParams(location.hash.slice(1)).get('invite');history.replaceState(null,'',location.pathname);
function notice(text){$('.toast').textContent=text;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('.toast').textContent='',7000)}
function errorText(e){return ({unauthorized:'Accesso scaduto. Richiedi un nuovo link privato.',invalid_invite:'Link scaduto o già usato. Richiedi un nuovo accesso.',sequence_conflict:'La conversazione è cambiata. Riaprila prima di inviare.',revision_conflict:'Esiste una versione più recente. La tua modifica non è stata sovrascritta.',run_active:'Nova sta già lavorando in questa conversazione.',agent_unavailable:'Servizio momentaneamente non disponibile.',runtime_interrupted:'Connessione interrotta. Il lavoro salvato resta disponibile.',provider_error:'Il modello non è disponibile. Nessuna risposta è stata inventata.',provider_timeout:'Il modello non ha risposto in tempo.',session_revoked:'La sessione è scaduta.',stale_context:'Il contenuto è cambiato durante il lavoro. Riapri e invia una nuova richiesta.',network:'Connessione interrotta: esito non confermato. Riapri la conversazione prima di riprovare.'})[e.message]||'Operazione non riuscita. I dati già salvati restano disponibili.'}
async function request(path,body,method='POST',key){let response;try{response=await fetch(path,{method:body===undefined?'GET':method,credentials:'same-origin',headers:body===undefined?{}:{'content-type':'application/json','x-nova-request':'1',...(key?{'idempotency-key':key}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{})})}catch{throw Error('network')}const data=await response.json();if(!response.ok){if(response.status===401&&!path.startsWith('/auth')){$('#shell').hidden=true;$('#login').hidden=false}throw Error(data.error||'request_failed')}return data}
const api=(p,b,m,k)=>request('/api'+p,b,m,k);
function elt(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n}
function download(text,name,type='text/plain;charset=utf-8'){const url=URL.createObjectURL(new Blob([text],{type}));const a=elt('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function canNavigate(){if(saving){notice('Attendi il salvataggio in corso.');return false}return !dirty||confirm('La modifica non è salvata. Vuoi lasciarla?')}
function mode(view){document.body.dataset.view=view;document.body.dataset.studio='';$('.studio').style.display='';$('.workspace').style.gridTemplateColumns='';}
function home(fresh=false){if(!canNavigate())return;dirty=false;++epoch;clearTimeout(timer);setBusy(false);mode('home');if(fresh)current=null;$('#crumb').textContent='Nuova conversazione';renderRecent()}
function renderRecent(){for(const selector of ['#recent','#homerecent']){const box=$(selector);box.replaceChildren();for(const c of workspace.conversations){const b=elt('button',c.title);b.addEventListener('click',()=>openConversation(c.id).catch(e=>notice(errorText(e))));box.append(b)}if(!workspace.conversations.length)box.append(elt('p','Le tue conversazioni compariranno qui.','capabilities'))}}
async function refresh(){workspace=await api('/workspace');renderRecent();return workspace}
function status(s){return ({queued:'In attesa',running:'Sto preparando',completed:'Risposta pronta',waiting_user:'Aspetto la tua risposta',cancelled:'Interrotto',failed:'Non completato',outcome_unknown:'Esito non confermato'})[s]||'Pronto'}
async function messages(id){let after=0,all=[];for(;;){const r=await api(`/conversations/${id}/messages?limit=50&after=${after}`);all.push(...r.items);if(r.nextAfter===null)return all;after=r.nextAfter}}
async function openConversation(id){if(!canNavigate())return;dirty=false;const e=++epoch;clearTimeout(timer);current=id;mode('work');$('#messages').replaceChildren();$('#activity').textContent='Carico la conversazione…';$('#paper').hidden=false;$('#editor').hidden=true;$('#save').hidden=true;artifact=null;revision=null;$('#artifacttitle').textContent='Il risultato apparirà qui';$('#artifacttext').textContent='Quando prepariamo una bozza, puoi leggerla e modificarla senza cambiare conversazione.';await refresh();if(e!==epoch)return;const list=await messages(id);if(e!==epoch)return;renderMessages(list);const c=workspace.conversations.find(c=>c.id===id);$('#title').textContent=c?.title||'Conversazione';$('#crumb').textContent=c?.title||'Conversazione';const latest=workspace.runs.find(r=>r.conversation_id===id);task=latest?.task_id??null;run=latest??null;$('#runstatus').textContent=status(run?.status);$('#activity').textContent=run?.error_code?errorText(Error(run.error_code)):'';renderCards();const a=workspace.artifacts.find(a=>a.conversation_id===id);if(a)await openArtifact(a.id,false);if(run&&['queued','running'].includes(run.status))poll(run.id,e);else setBusy(false)}
function renderMessages(list){const box=$('#messages');box.replaceChildren();for(const m of list){if(m.role==='assistant'){const label=elt('div','NOVA','speaker');box.append(label)}box.append(elt('div',m.text,m.role==='user'?'user msg':'reply msg'))}sequence=list.at(-1)?.sequence||0}
function renderCards(){for(const n of $('#messages').querySelectorAll('.resultcard'))n.remove();for(const a of workspace.artifacts.filter(a=>a.conversation_id===current)){const c=elt('div',undefined,'resultcard');c.append(elt('strong',a.title),elt('p',`Bozza da controllare · Versione ${a.current_revision}`,'capabilities'));const b=elt('button','Apri risultato →');b.onclick=()=>openArtifact(a.id,true).catch(e=>notice(errorText(e)));c.append(b);$('#messages').append(c)}}
function setBusy(value){busy=value;for(const b of document.querySelectorAll('[data-action="sendhome"],[data-action="sendchat"]'))b.disabled=value;$('#cancel').hidden=!value;}
async function send(from){const input=$(from),text=input.value.trim();if(!text||busy)return;if(dirty){notice('Salva o annulla la modifica del risultato prima di continuare.');return}setBusy(true);let id=current;try{if(!id||from==='#homeinput'){const c=await api('/conversations',{title:text.slice(0,80)},'POST',crypto.randomUUID());id=c.id;current=id;sequence=0;task=null;run=null;mode('work');$('#messages').replaceChildren();$('#title').textContent=c.title;$('#crumb').textContent=c.title;}const e=++epoch;const body={baseSequence:sequence,text,...(task&&run?.status!=='completed'?{taskId:task}:{})};$('#activity').textContent='Invio in corso…';const result=await api(`/conversations/${id}/turns`,body,'POST',crypto.randomUUID());input.value='';task=result.taskId;run={...result,task_id:result.taskId};const list=await messages(id);if(e!==epoch)return;renderMessages(list);poll(result.id,e)}catch(err){setBusy(false);$('#activity').textContent=errorText(err);notice(errorText(err));await refresh().catch(()=>{});}}
async function poll(id,e){if(e!==epoch)return;setBusy(true);try{const r=await api('/runs/'+id);if(e!==epoch)return;run={...r,task_id:r.taskId};$('#runstatus').textContent=status(r.status);const events=await api(`/runs/${id}/events?limit=50`);if(e!==epoch)return;const kinds=events.items.map(x=>x.kind);$('#activity').textContent=r.error?errorText(Error(r.error)):kinds.includes('tool.succeeded')?'Risultato salvato. Sto preparando la risposta.':status(r.status);if(['queued','running'].includes(r.status)){timer=setTimeout(()=>poll(id,e),1200);return}await refresh();const list=await messages(current);if(e!==epoch)return;renderMessages(list);renderCards();const a=workspace.artifacts.find(a=>a.conversation_id===current);if(a&&!dirty)await openArtifact(a.id,false);setBusy(false);$('#activity').textContent=r.error?errorText(Error(r.error)):r.status==='waiting_user'?'Puoi continuare rispondendo qui sotto.':'';}catch(err){setBusy(false);$('#activity').textContent=errorText(err);notice(errorText(err))}}
async function openArtifact(id,show=true,version){if(!canNavigate())return;const a=workspace.artifacts.find(a=>a.id===id);if(!a)return;const e=epoch,requestId=++artifactRequest;const r=await api(`/artifacts/${id}/revisions/${version||a.current_revision}`);if(e!==epoch||requestId!==artifactRequest||dirty)return;artifact=a;revision=r;dirty=false;$('#artifacttitle').textContent=a.title;$('#artifacttext').textContent=r.content.text;$('#revisionlabel').textContent=`Versione ${r.revision} · ${r.content.language}`;$('#saved').textContent='Versione salvata';$('#editor').value=r.content.text;$('#editor').hidden=true;$('#paper').hidden=false;$('#save').hidden=true;$('#download').hidden=false;$('#versions').hidden=true;if(show){document.body.dataset.studio='open';$('.studio').style.display='';$('.workspace').style.gridTemplateColumns='';}}
async function save(){if(!artifact||!revision||!dirty)return;const id=artifact.id,e=epoch,text=$('#editor').value,base=revision.revision;saving=true;$('#save').disabled=true;$('#editor').disabled=true;try{await api(`/artifacts/${id}/revisions`,{baseRevision:base,content:{text,language:revision.content.language}},'POST',crypto.randomUUID());saving=false;dirty=false;await refresh();if(e===epoch){await openArtifact(id,true);notice('Modifica salvata in una nuova versione.')}}catch(err){notice(errorText(err));$('#saved').textContent='Modifica non confermata. Il testo resta nell’editor.'}finally{saving=false;$('#save').disabled=false;$('#editor').disabled=false}}
$('#editor').addEventListener('input',()=>{dirty=true;$('#saved').textContent='Modifica non salvata'});$('#save').onclick=save;
$('#cancel').onclick=async()=>{if(run)try{await api('/runs/'+run.id+'/cancel',{},'POST',crypto.randomUUID());notice('Richiesta interrotta. I risultati già salvati restano disponibili.')}catch(e){notice(errorText(e))}};
$('#file').onchange=async()=>{const f=$('#file').files[0];if(!f)return;try{if(!f.name.endsWith('.txt')||f.size>16384)throw Error('file');if(!current){const c=await api('/conversations',{title:'Documento di testo'},'POST',crypto.randomUUID());current=c.id;await openConversation(c.id)}const id=current;const bytes=new Uint8Array(await f.arrayBuffer());const dataBase64=btoa(String.fromCharCode(...bytes));const name=f.name.replace(/[^A-Za-z0-9_-]/g,'_').slice(0,50)+'.txt';await api('/files',{conversationId:id,name,mime:'text/plain',dataBase64},'POST',crypto.randomUUID());notice('File salvato. Ora scrivi cosa vuoi farne.');}catch{notice('File non caricato. Sono accettati solo .txt UTF-8, massimo 16 KB.')}finally{$('#file').value=''}};
document.addEventListener('click',async e=>{const b=e.target.closest('button[data-action]');if(!b)return;try{switch(b.dataset.action){case'home':home();break;case'new':home(true);break;case'sendhome':await send('#homeinput');break;case'sendchat':await send('#chatinput');break;case'cv':$('#homeinput').value='Aiutami a preparare il mio curriculum. Fammi una domanda alla volta e salva una bozza senza inventare dati.';$('#homeinput').focus();break;case'explain':$('#homeinput').value='Vorrei capire un testo. Posso incollarlo qui?';$('#homeinput').focus();break;case'voice':notice('La conversazione vocale non è ancora disponibile. Puoi usare la dettatura della tastiera del telefono.');break;case'languages':notice('Puoi parlare con Nova in italiano, বাংলা o English. La lingua dell’interfaccia per ora è italiano.');break;case'upload':$('#file').click();break;case'back':if(!canNavigate())return;++artifactRequest;dirty=false;document.body.dataset.studio='';if(innerWidth>700){$('.studio').style.display='none';$('.workspace').style.gridTemplateColumns='1fr'}break;case'edit':++artifactRequest;if(!revision){notice('Apri prima un risultato.');break}if(run&&['queued','running'].includes(run.status)){notice('Attendi la fine del lavoro prima di modificare.');break}$('#editor').hidden=false;$('#paper').hidden=true;$('#save').hidden=false;$('#download').hidden=true;break;case'preview':++artifactRequest;if(revision&&canNavigate()){dirty=false;$('#editor').value=revision.content.text;$('#editor').hidden=true;$('#paper').hidden=false;$('#save').hidden=true;$('#download').hidden=false}break;case'versions':if(!artifact)break;$('#versions').replaceChildren();$('#versions').hidden=false;for(let v=artifact.current_revision;v>Math.max(0,artifact.current_revision-20);v--){const n=elt('button','v'+v);n.onclick=()=>openArtifact(artifact.id,true,v).catch(e=>notice(errorText(e)));$('#versions').append(n)}break;case'download':if(revision)download(revision.content.text,`nova-risultato-v${revision.revision}.txt`);break;case'print':if(revision&&!dirty)window.print();else notice('Salva la modifica prima di stampare.');break;case'results':home();$('#homerecent').replaceChildren();for(const a of workspace.artifacts){const n=elt('button',a.title+' →');n.onclick=async()=>{await openConversation(a.conversation_id);await openArtifact(a.id,true)};$('#homerecent').append(n)}break;case'exportdata':download(JSON.stringify(await api('/me/export'),null,2),'nova-i-miei-dati.json','application/json');break;case'logout':await request('/auth/logout',{});location.reload();break;}}catch(err){notice(errorText(err))}});
for(const id of ['#homeinput','#chatinput'])$(id).onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();send(id)}};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
async function start(){try{await refresh();$('#login').hidden=true;$('#shell').hidden=false;home(true)}catch{$('#shell').hidden=true;$('#login').hidden=false;if(invite){$('#logintext').textContent='Hai un invito personale. Apri il tuo spazio per iniziare. Il link può essere usato una sola volta.';$('#enter').hidden=false;$('#enter').onclick=async()=>{try{$('#enter').disabled=true;await request('/auth/exchange',{invite});await start()}catch(e){$('#logintext').textContent=errorText(e)}finally{$('#enter').disabled=false}}}}}
start();
