import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {chromium} from 'playwright';
test('staged native renderer presents dated records and search links separately with safe metadata',async()=>{
 const code=await readFile(new URL('../staging/jobs-generic-1/app.js',import.meta.url),'utf8');const match=code.match(/function renderJobReceipts\(events\)\{[\s\S]*?\n\}/);assert.ok(match);
 const browser=await chromium.launch({headless:true});try{const page=await browser.newPage();await page.setContent('<div id="messages"></div>');await page.addScriptTag({content:"const $=s=>document.querySelector(s);function elt(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n}"+match[0]});
 const event=(result:any)=>({kind:'tool.succeeded',detail:{tool:'jobs_search',result}});
 const events=[event({status:'search_links_only',occupation:'saldatore',requestedCity:'Jesi',notice:'Non sono annunci',searchLinks:[{title:'Subito — ricerca nazionale',url:'https://www.subito.it/annunci-italia/vendita/offerte-lavoro/?q=saldatore+Jesi',discoveredAt:'2026-09-30',kind:'BROWSING_SUGGESTION'},{title:'bad',url:'javascript:alert(1)'}]}),event({status:'collected_results',occupation:'saldatore',opportunities:[{title:'<img src=x onerror=alert(1)>',city:'Jesi',province:'AN',publisher_type:'UNKNOWN',source_url:'https://example.org/job/1',sourceName:'Permitted source',status:'UNKNOWN',discovered_at:'2024-01-01',last_verified_at:null}]}),event({status:'needs_city',question:'In quale città?'})];
 await page.evaluate(events=>(window as any).renderJobReceipts(events),events);assert.equal(await page.locator('a').count(),2);assert.equal(await page.locator('img').count(),0);const text=await page.locator('#messages').innerText();for(const s of ['Jesi','AN','saldatore','2024-01-01','Inserzionista sconosciuto','Ricerca','non verificata','In quale città?'])assert.ok(text.includes(s),s);assert.equal(await page.locator('a').first().getAttribute('rel'),'noopener noreferrer');
 await page.evaluate(events=>(window as any).renderJobReceipts(events),events);assert.equal(await page.locator('a').count(),2);
 }finally{await browser.close()}
});
