import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {buildApp,bootstrap,migrate,hash} from '../src/app.ts';import {database,request} from './helpers.ts';
const call=()=>({id:randomUUID(),type:'function' as const,function:{name:'jobs_search',arguments:JSON.stringify({query:'saldatore',city:'Jesi'})}});
async function settled(pool:any,id:string){for(let i=0;i<500;i++){const r=(await pool.query('SELECT * FROM agent_runs WHERE id=$1',[id])).rows[0];if(r&&!['queued','running'].includes(r.status))return r;await new Promise(r=>setTimeout(r,10));}throw Error('timeout')}
for(const action of ['revoke','cancel'])test(`generic discovery ${action} fences page reads and receipts after web await`,async()=>{
 const db=await database();await migrate(db.pool);const user=await bootstrap(db.pool);let enter!:()=>void,release!:()=>void;const started=new Promise<void>(r=>enter=r),gate=new Promise<void>(r=>release=r);let pages=0;
 const app=buildApp(db.pool,{agent:{endpoint:'https://example.org',model:'controlled',jobPageAccess:{authorizedOrigins:['https://job.hnh.it'],fetcher:async()=>{pages++;return new Response('<h1>Saldatore</h1>Luogo di lavoro Jesi, Italia')}},search:async()=>{enter();await gate;return {sources:[{title:'Saldatore',url:'https://job.hnh.it/jobs/saldatore-123.htm'}]}},provider:{complete:async()=>({role:'assistant',content:null,tool_calls:[call()]})}}} as any);
 try{const base=await app.listen({port:0,host:'127.0.0.1'});const c=(await request(base,'/conversations',user.token,{title:'Jobs'},'POST',randomUUID())).body;const t=(await request(base,`/conversations/${c.id}/turns`,user.token,{baseSequence:0,text:'cerco saldatore a Jesi'},'POST',randomUUID())).body;await started;
 if(action==='revoke')await db.pool.query('DELETE FROM sessions WHERE token_hash=$1',[hash(user.token)]);else await request(base,`/runs/${t.id}/cancel`,user.token,{},'POST',randomUUID());release();await settled(db.pool,t.id);assert.equal(pages,0);assert.equal((await db.pool.query('SELECT * FROM agent_tool_receipts WHERE run_id=$1',[t.id])).rowCount,0);
 }finally{release();await app.close();await db.close()}
});
test('permitted imported metadata survives actual native receipt/event persistence',async()=>{
 const db=await database();await migrate(db.pool);const user=await bootstrap(db.pool);const app=buildApp(db.pool,{agent:{endpoint:'https://example.org',model:'controlled',jobRecords:[{occupation:'saldatore',title:'Saldatore TIG',city:'Jesi',province:'AN',url:'https://example.org/job/1',sourceName:'Permitted test import',permission:'permitted_import',collectedAt:'2024-01-01T00:00:00Z'}],provider:{complete:async(m:any[])=>m.at(-1).role==='tool'?{role:'assistant',content:'Osservazione importata; disponibilità non verificata.'}:{role:'assistant',content:null,tool_calls:[call()]}}}} as any);
 try{const base=await app.listen({port:0,host:'127.0.0.1'});const c=(await request(base,'/conversations',user.token,{title:'Jobs'},'POST',randomUUID())).body;const t=(await request(base,`/conversations/${c.id}/turns`,user.token,{baseSequence:0,text:'saldatore a Jesi'},'POST',randomUUID())).body;const run=await settled(db.pool,t.id);assert.equal(run.status,'completed');const e=await request(base,`/runs/${run.id}/events?limit=50`,user.token);const r=e.body.items.find((e:any)=>e.detail?.tool==='jobs_search').detail.result;assert.equal(r.status,'collected_results');assert.equal(r.opportunities[0].province,'AN');assert.equal(r.opportunities[0].publisher_type,'UNKNOWN');assert.equal(r.opportunities[0].discovered_at,'2024-01-01T00:00:00Z');assert.equal(r.opportunities[0].last_verified_at,null);
 }finally{await app.close();await db.close()}
});
