import test from 'node:test';import assert from 'node:assert/strict';import {chromium} from 'playwright';import {readFile} from 'node:fs/promises';import {resolve} from 'node:path';
declare let workspace:any;declare let current:string;declare let task:string;declare let run:any;declare function send(from:string):Promise<void>;declare function renderCards():void;
test('staged native voice UI binds conversation, stops late connection and provides authenticated file downloads',async()=>{
 const browser=await chromium.launch({headless:true,args:['--no-sandbox']});try{const page=await browser.newPage();page.on('pageerror',e=>console.log('PAGEERROR',e.message));const sent:any[]=[];
 await page.route('https://nova.test/**',async route=>{const u=new URL(route.request().url());if(u.pathname==='/'){let html=await readFile('public/index.html','utf8');html=html.replace('</head>','<script src="/native.js" defer></script></head>');return route.fulfill({body:html,contentType:'text/html'})}if(u.pathname==='/native.js'){let body='';try{body=await readFile('staging/voice-files/public/native.js','utf8')}catch{}return route.fulfill({body,contentType:'text/javascript'})}if(u.pathname.startsWith('/api/')){const p=u.pathname.slice(4);sent.push({path:p,body:route.request().postDataJSON()});if(p.startsWith('/providers'))return route.fulfill({json:{selection:{provider:'nova',model:'controlled'},connections:[],catalog:[]}});if(p.endsWith('/download'))return route.fulfill({body:'console.log("download");',contentType:'application/octet-stream'});if(/^\/tasks\//.test(p))return route.fulfill({json:{status:'active'}});if(p==='/files/upload')return route.fulfill({status:201,json:{extraction:{status:'unsupported',reason:'Binary stored only'}}});if(p==='/workspace')return route.fulfill({json:{conversations:[],artifacts:[],runs:[]}});if(p==='/conversations')return route.fulfill({json:{id:'11111111-1111-4111-8111-111111111111',title:'Voice'}});if(p.endsWith('/messages'))return route.fulfill({json:{items:[],nextAfter:null}});if(p==='/voice/sessions')return route.fulfill({status:201,json:{id:'22222222-2222-4222-8222-222222222222',sdp:'answer',maxSeconds:180}});return route.fulfill({json:{status:'stopped'}})}try{return route.fulfill({body:await readFile(resolve('public',u.pathname.slice(1))),contentType:u.pathname.endsWith('.js')?'text/javascript':'text/css'})}catch{return route.fulfill({status:404,body:''})}});
 await page.addInitScript('window.__name = (v) => v');
 await page.addInitScript(()=>{const state={stopped:0,closed:0};(window as any).fixture=state;const track={enabled:true,stop(){state.stopped++}};Object.defineProperty(navigator,'mediaDevices',{value:{getUserMedia:async()=>({getTracks:()=>[track],getAudioTracks:()=>[track]})}});(window as any).RTCPeerConnection=class{localDescription={sdp:'synthetic-offer'};connectionState='connected';addTrack(){}createDataChannel(){const c:any={readyState:'open',close(){state.closed++}};setTimeout(()=>c.onopen?.(),50);return c}async createOffer(){return {sdp:'synthetic-offer'}}async setLocalDescription(){}async setRemoteDescription(){}close(){state.closed++}}});
 await page.goto('https://nova.test/');await page.waitForFunction(()=>!(document.querySelector('#shell') as HTMLElement).hidden);await page.getByRole('button',{name:'Chat vocale',exact:true}).click();await page.getByRole('button',{name:'Avvia microfono',exact:true}).click();await page.waitForTimeout(300);
 assert.ok(sent.some(x=>x.path==='/voice/sessions'&&x.body.conversationId==='11111111-1111-4111-8111-111111111111'),'must use bound native session route, not legacy /voice/connect');await page.getByRole('button',{name:'Termina sessione',exact:true}).click();await page.waitForTimeout(100);assert.ok(sent.some(x=>x.path.endsWith('/stop')));assert.ok((await page.evaluate(()=>(window as any).fixture.stopped))>0);
 assert.equal(await page.locator('#file').getAttribute('accept'),null);await page.locator('#file').setInputFiles({name:'unknown.dat',mimeType:'application/octet-stream',buffer:Buffer.from([255,0,1])});await page.waitForSelector('.attachment-chip:visible');assert.ok(!sent.some(x=>x.path==='/files/upload'),'attachment is staged, not uploaded until the user sends');assert.match(await page.locator('.attachment-chip:visible').innerText(),/unknown\.dat/);await page.locator('.attachment-chip:visible button[aria-label="Rimuovi allegato"]').click();
 await page.evaluate(()=>{workspace={conversations:[],runs:[],artifacts:[{id:'33333333-3333-4333-8333-333333333333',title:'Plain draft',current_revision:1,conversation_id:current}]};renderCards()});assert.equal(await page.getByText('Scarica file generato',{exact:true}).count(),0,'ordinary drafts must not offer nonexistent generated downloads');
 await page.evaluate(()=>{workspace.artifacts[0].file={name:'real.js',format:'text'};renderCards()});const gotDownload=page.waitForEvent('download');await page.getByText('Scarica file generato',{exact:true}).click();const downloaded=await gotDownload;assert.equal(downloaded.suggestedFilename(),'real.js');assert.equal(await readFile((await downloaded.path())!,'utf8'),'console.log("download");');
 await page.evaluate(()=>{current='11111111-1111-4111-8111-111111111111';task='44444444-4444-4444-8444-444444444444';run={status:'completed'};(document.querySelector('#chatinput') as HTMLTextAreaElement).value='Correct the saved file';});await page.evaluate(()=>send('#chatinput'));assert.equal(sent.findLast(x=>x.path.endsWith('/turns'))?.body.taskId,'44444444-4444-4444-8444-444444444444');
 }finally{await browser.close()}
});
