import test from 'node:test';import assert from 'node:assert/strict';import {EventEmitter} from 'node:events';import {randomUUID} from 'node:crypto';import {database} from './helpers.ts';import {buildApp,bootstrap,migrate} from '../src/app.ts';
class Speech extends EventEmitter{sent:any[]=[];closed=false;send(e:any){this.sent.push(e)}close(){this.closed=true}input(id:string,text:string){this.emit('event',{type:'input_audio_buffer.committed',item_id:id});this.emit('event',{type:'conversation.item.input_audio_transcription.completed',item_id:id,transcript:text})}}
async function fixture(held=false){const db=await database();await migrate(db.pool);const owner=await bootstrap(db.pool),other=await bootstrap(db.pool);const speech=new Speech();let release!:(v:any)=>void;let count=0;const inputs:any[]=[];let providerSignal:AbortSignal;const app=buildApp(db.pool,{agent:{endpoint:'https://fixture.invalid',model:'controlled',voice:{connect:async()=>({sdp:'answer',transport:speech})},provider:{complete:async(messages:any,_tools:any,signal:AbortSignal)=>{providerSignal=signal;inputs.push(messages);if(held)return new Promise(r=>release=r);if(++count===1)return {role:'assistant',content:null,tool_calls:[{id:'file',type:'function',function:{name:'create_file',arguments:JSON.stringify({name:'voice.js',format:'text',text:'console.log("voice");\n',entries:[]})}}]};return {role:'assistant',content:'Saved voice.js.'}}}}} as any);await app.ready();const send=(url:string,payload?:any,token=owner.token,key=randomUUID())=>app.inject({url,method:payload?'POST':'GET',headers:{authorization:`Bearer ${token}`,'idempotency-key':key},payload});const c=(await send('/conversations',{title:'Mixed channels'})).json();return {db,app,owner,other,speech,inputs,send,c,get signal(){return providerSignal},release:(v:any)=>release(v),close:async()=>{await app.close();await db.close()}}}
test('failed canonical tool never speaks success and exposes voice run failure',async()=>{const f=await fixture(true);try{const s=(await f.send('/voice/sessions',{conversationId:f.c.id,sdp:'synthetic-offer',language:'en'})).json();f.speech.input('bad','Create file');await wait(async()=>f.inputs.length===1);f.release({role:'assistant',content:null,tool_calls:[{id:'bad',type:'function',function:{name:'execute_shell',arguments:'{}'}}]});await wait(async()=>(await f.send('/voice/sessions/'+s.id)).json().status==='failed');assert.equal(f.speech.sent.some(e=>e.type==='response.create'),false);assert.equal((await f.db.pool.query("SELECT count(*)::int n FROM messages WHERE role='assistant'")).rows[0].n,0)}finally{await f.close()}});
test('cancelled voice inference is promptly aborted, not merely hidden until provider timeout',async()=>{const f=await fixture(true);try{const s=(await f.send('/voice/sessions',{conversationId:f.c.id,sdp:'synthetic-offer',language:'auto'})).json();f.speech.input('cancel','Hold');await wait(async()=>f.inputs.length===1);await f.send('/voice/sessions/'+s.id+'/stop',{});await wait(async()=>f.signal.aborted);assert.equal(f.signal.aborted,true)}finally{await f.close()}});
async function wait(fn:()=>Promise<boolean>){for(let n=0;n<200;n++){if(await fn())return;await new Promise(r=>setTimeout(r,10))}assert.fail('bounded wait expired')}
test('provider-observed committed voice input uses native tools, persists once, and continues in text',async()=>{const f=await fixture();try{const s=await f.send('/voice/sessions',{conversationId:f.c.id,sdp:'synthetic-offer',language:'auto'});assert.equal(s.statusCode,201,s.body);
 f.speech.emit('event',{type:'input_audio_buffer.speech_started'});assert.equal(f.speech.sent.some(e=>e.type==='response.cancel'),false,'no cancellation when no response exists');
 f.speech.emit('event',{type:'response.output_audio_transcript.done',transcript:'Never user input'});f.speech.emit('event',{type:'conversation.item.input_audio_transcription.completed',item_id:'forged',transcript:'Not bound to audio'});
 f.speech.input('audio-one','Create voice.js');f.speech.input('audio-one','Create voice.js');
 await wait(async()=>Number((await f.db.pool.query("SELECT count(*) n FROM agent_runs WHERE status='completed'")).rows[0].n)===1);
 const ms=(await f.send(`/conversations/${f.c.id}/messages`)).json().items;assert.deepEqual(ms.map((m:any)=>[m.role,m.channel,m.provenance]),[['user','voice','provider_transcribed_audio'],['assistant','voice','agent_generated']]);assert.equal(ms.length,2);
 assert.equal((await f.send('/sources',{conversationId:f.c.id,messageId:ms[1].id})).statusCode,409);
 const receipts=(await f.db.pool.query('SELECT result FROM agent_tool_receipts')).rows;assert.equal(receipts.length,1);assert.equal((await f.send(receipts[0].result.download)).body,'console.log("voice");\n');await wait(async()=>f.speech.sent.some(e=>e.type==='response.create'&&JSON.stringify(e).includes('Saved voice.js.')));
 assert.equal((await f.send('/voice/sessions/'+s.json().id,undefined,f.other.token)).statusCode,404);
 const turn=await f.send(`/conversations/${f.c.id}/turns`,{baseSequence:2,text:'Continue in text.'});assert.equal(turn.statusCode,201);await wait(async()=>(await f.send('/runs/'+turn.json().id)).json().status==='completed');assert.ok(JSON.stringify(f.inputs.at(-1)).includes('Create voice.js'));assert.equal((await f.send(`/conversations/${f.c.id}/messages`)).json().items.length,4);
 await f.send('/voice/sessions/'+s.json().id+'/stop',{});f.speech.input('late','Must not persist');await new Promise(r=>setTimeout(r,40));assert.equal((await f.send(`/conversations/${f.c.id}/messages`)).json().items.length,4);assert.equal(f.speech.closed,true);
 }finally{await f.close()}});
test('stop during native inference fences late voice tool completion',async()=>{const f=await fixture(true);try{const s=(await f.send('/voice/sessions',{conversationId:f.c.id,sdp:'synthetic-offer',language:'en'})).json();assert.ok(s.id);f.speech.input('held','Create file');await wait(async()=>f.inputs.length===1);f.speech.emit('event',{type:'input_audio_buffer.speech_started'});await wait(async()=>(await f.db.pool.query('SELECT status FROM agent_runs')).rows[0]?.status==='cancelled');await f.send('/voice/sessions/'+s.id+'/stop',{});f.release({role:'assistant',content:'Late output'});await wait(async()=>(await f.db.pool.query('SELECT status FROM agent_runs')).rows[0]?.status==='cancelled');assert.equal((await f.db.pool.query("SELECT count(*)::int n FROM messages WHERE role='assistant'")).rows[0].n,0)}finally{await f.close()}});
