'use strict';
const $=s=>document.querySelector(s);let workspace={conversations:[],artifacts:[],runs:[]},current=null,sequence=0,task=null,run=null,epoch=0,busy=false,artifact=null,revision=null,dirty=false,saving=false,artifactRequest=0,timer,noticeTimer;
const invite=new URLSearchParams(location.hash.slice(1)).get('invite');history.replaceState(null,'',location.pathname);
function notice(text){$('.toast').textContent=text;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('.toast').textContent='',7000)}
function errorText(e){return ({unauthorized:'Accesso scaduto. Richiedi un nuovo link privato.',invalid_invite:'Link scaduto o già usato. Richiedi un nuovo accesso.',sequence_conflict:'La conversazione è cambiata. Riaprila prima di inviare.',revision_conflict:'Esiste una versione più recente. La tua modifica non è stata sovrascritta.',run_active:'Nova sta già lavorando in questa conversazione.',agent_unavailable:'Servizio momentaneamente non disponibile.',runtime_interrupted:'Connessione interrotta. Il lavoro salvato resta disponibile.',provider_error:'Il modello non è disponibile. Nessuna risposta è stata inventata.',provider_timeout:'Il modello non ha risposto in tempo.',session_revoked:'La sessione è scaduta.',stale_context:'Il contenuto è cambiato durante il lavoro. Riapri e invia una nuova richiesta.',network:'Connessione interrotta: esito non confermato. Riapri la conversazione prima di riprovare.'})[e.message]||'Operazione non riuscita. I dati già salvati restano disponibili.'}
async function request(path,body,method='POST',key){let response;try{response=await fetch(path,{method:body===undefined?'GET':method,credentials:'same-origin',headers:body===undefined?{}:{'content-type':'application/json','x-nova-request':'1',...(key?{'idempotency-key':key}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{})})}catch{throw Error('network')}const data=await response.json();if(!response.ok){if(response.status===401&&!path.startsWith('/auth')){$('#shell').hidden=true;$('#login').hidden=false}throw Error(data.error||'request_failed')}return data}
const api=(p,b,m,k)=>request('/api'+p,b,m,k);
function elt(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n}
function download(text,name,type='text/plain;charset=utf-8'){const url=URL.createObjectURL(new Blob([text],{type}));const a=elt('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function canNavigate(){if(saving){notice('Attendi il salvataggio in corso.');return false}return !dirty||confirm('La modifica non è salvata. Vuoi lasciarla?')}
function mode(view){document.body.dataset.view=view;document.body.classList.remove('dashboard-open');document.body.dataset.studio='';$('.studio').style.display='';$('.workspace').style.gridTemplateColumns='';}
function home(fresh=false){if(!canNavigate())return;dirty=false;++epoch;clearTimeout(timer);setBusy(false);if(fresh&&window.openDashboard){current=null;window.openDashboard();renderRecent();return}mode('home');if(fresh)current=null;$('#crumb').textContent='Nuova conversazione';renderRecent()}
function renderRecent(){for(const selector of ['#recent','#homerecent']){const box=$(selector);box.replaceChildren();for(const c of workspace.conversations){const b=elt('button',c.title);b.addEventListener('click',()=>openConversation(c.id).catch(e=>notice(errorText(e))));box.append(b)}if(!workspace.conversations.length)box.append(elt('p','Le tue conversazioni compariranno qui.','capabilities'))}}
async function refresh(){workspace=await api('/workspace');renderRecent();return workspace}
function status(s){return ({queued:'In attesa',running:'Sto preparando',completed:'Risposta pronta',waiting_user:'Aspetto la tua risposta',cancelled:'Interrotto',failed:'Non completato',outcome_unknown:'Esito non confermato'})[s]||'Pronto'}
async function messages(id){let after=0,all=[];for(;;){const r=await api(`/conversations/${id}/messages?limit=50&after=${after}`);all.push(...r.items);if(r.nextAfter===null)return all;after=r.nextAfter}}
async function openConversation(id){if(!canNavigate())return;dirty=false;const e=++epoch;clearTimeout(timer);current=id;mode('work');$('#messages').replaceChildren();$('#activity').textContent='Carico la conversazione…';$('#paper').hidden=false;$('#editor').hidden=true;$('#save').hidden=true;artifact=null;revision=null;$('#artifacttitle').textContent='Il risultato apparirà qui';$('#artifacttext').textContent='Quando prepariamo una bozza, puoi leggerla e modificarla senza cambiare conversazione.';await refresh();if(e!==epoch)return;const list=await messages(id);if(e!==epoch)return;renderMessages(list);const c=workspace.conversations.find(c=>c.id===id);$('#title').textContent=c?.title||'Conversazione';$('#crumb').textContent=c?.title||'Conversazione';const latest=workspace.runs.find(r=>r.conversation_id===id);task=latest?.task_id??null;run=latest??null;if(run){const events=await api(`/runs/${run.id}/events?limit=50`);if(e!==epoch)return;renderJobReceipts(events.items);}$('#runstatus').textContent=status(run?.status);$('#activity').textContent=run?.error_code?errorText(Error(run.error_code)):'';renderCards();const a=workspace.artifacts.find(a=>a.conversation_id===id);if(a)await openArtifact(a.id,false);if(run&&['queued','running'].includes(run.status))poll(run.id,e);else setBusy(false)}
function renderMessages(list){const box=$('#messages');box.replaceChildren();for(const m of list){if(m.role==='assistant'){const label=elt('div','NOVA','speaker');box.append(label)}box.append(elt('div',m.text,m.role==='user'?'user msg':'reply msg'))}sequence=list.at(-1)?.sequence||0}
function renderJobReceipts(events){
 const box=$('#messages');for(const old of box.querySelectorAll('.job-receipt'))old.remove();const seen=new Set();
 const safe=raw=>{try{const u=new URL(raw);return u.protocol==='https:'&&!u.username&&!u.password&&!u.port&&!/^(?:localhost|\[|\d)/.test(u.hostname)&&!/\.(?:local|internal)$/.test(u.hostname)}catch{return false}};
 const day=v=>typeof v==='string'&&v.length>=10?v.slice(0,10):null;
 const host=u=>{try{return new URL(u).hostname.replace(/^www\./,'')}catch{return 'fonte originale'}};
 const nice=v=>{const d=day(v);if(!d)return null;const [y,m,g]=d.split('-');return `${g}/${m}/${y}`};
 const contract=v=>{if(!v)return null;const map={FULL_TIME:'Tempo pieno',PART_TIME:'Part time',TEMPORARY:'Temporaneo',CONTRACTOR:'Collaborazione',INTERN:'Stage',PER_DIEM:'A giornata',VOLUNTEER:'Volontariato',OTHER:'Altro'};return String(v).split(/[\s,]+/).filter(Boolean).map(x=>map[x.toUpperCase()]||x.toLowerCase().replace(/_/g,' ')).join(', ')};
 const card=o=>{if(seen.has(o.key))return;seen.add(o.key);
  const c=elt('article',undefined,'resultcard job-receipt job-card'+(o.kind?' job-card-'+o.kind:''));
  const head=elt('div',undefined,'job-card-head');const badges=elt('div',undefined,'job-badges');for(const b of o.badges||[])if(b&&b.text)badges.append(elt('span',b.text,'job-badge'+(b.kind?' job-badge-'+b.kind:'')));if(badges.childElementCount)head.append(badges);
  head.append(elt('h4',o.title||'Senza titolo','job-title'));if(o.subtitle)head.append(elt('p',o.subtitle,'job-subtitle'));c.append(head);
  const facts=elt('dl',undefined,'job-facts');for(const f of o.facts||[])if(f&&f.value){facts.append(elt('dt',f.label));facts.append(elt('dd',f.value))}if(facts.childElementCount)c.append(facts);
  for(const n of o.notes||[])if(n)c.append(elt('p',n,'job-note capabilities'));
  if(o.url&&safe(o.url)){const a=elt('a',o.label,'job-cta');a.href=o.url;a.target='_blank';a.rel='noopener noreferrer';c.append(a)}
  box.append(c)};
 for(const event of events){if(event.kind!=='tool.succeeded'||event.detail?.tool!=='jobs_search')continue;const r=event.detail.result;if(!r)continue;
 const req=r.requestedCity||r.city;const context=`${r.occupation||'Ruolo da chiarire'} · ${req||(r.remote?'Remoto':'Città da chiarire')}`;
 const opportunities=(r.opportunities||[]).filter(o=>safe(o.source_url));
 const explain=r.status!=='ok'||!opportunities.length;
 if(r.question||(explain&&(r.notice||r.sourceUnavailable)))card({kind:'notice',title:r.question||context,subtitle:r.question?context:null,notes:[explain?r.notice:null,explain&&r.sourceUnavailable?`Fonte non disponibile: ${r.sourceUnavailable.code||'motivo non dichiarato'}`:null],key:JSON.stringify([r.status,context,r.question])});
 if(opportunities.length){const rank=o=>o.locationMatch==='CITY'?0:o.locationMatch==='PROVINCE_OR_REGION'?1:o.locationMatch==='MISMATCH'?3:2;opportunities.sort((a,b)=>rank(a)-rank(b));
  const key='summary:'+context+(r.moreOffers?':more':'');if(!seen.has(key)){seen.add(key);const s=elt('div',undefined,'job-receipt job-summary');s.append(elt('strong',`${opportunities.length} ${opportunities.length===1?'annuncio trovato':'annunci trovati'}${r.moreOffers?' · ricerca estesa':''}`),elt('span',context));if(r.moreOffers&&r.subito?.pagesRead>1)s.append(elt('span',`${r.subito.pagesRead} pagine Subito lette`));if(typeof r.adzuna?.count==='number'&&r.adzuna.count>opportunities.length)s.append(elt('span',`Adzuna segnala ${r.adzuna.count} annunci in totale`));const city=opportunities.filter(o=>o.locationMatch==='CITY').length;if(req&&city<opportunities.length)s.append(elt('span',`${city} a ${req} · ${opportunities.length-city} in provincia o altrove`));const off=r.subito?.offQuery;if(off)s.append(elt('span',`${off} non pertinenti esclusi`));box.append(s)}}
 const place=o=>{const loc=o.observedLocality||o.city||'Località non dichiarata';const prov=o.observedProvince||o.province||o.observedRegion;return `${loc}${prov?' ('+prov+')':''}`};
 const placeBadge=o=>o.locationMatch==='CITY'?{text:req||place(o),kind:'place'}:o.locationMatch==='PROVINCE_OR_REGION'?{text:`Provincia · non ${req||'il comune richiesto'}`,kind:'place'}:o.locationMatch==='MISMATCH'?{text:`Altra località · non ${req||'il comune richiesto'}`,kind:'warn'}:null;
 const publisher=o=>o.publisher_type==='DIRECT_EMPLOYER'?'Datore diretto con evidenza':o.publisher_type==='UNKNOWN'?'Inserzionista sconosciuto':o.publisher_type==='STAFFING_AGENCY'?'Agenzia per il lavoro':o.publisher_type==='AGENCY'?'Agenzia':o.publisher_type||'Inserzionista sconosciuto';
 for(const o of opportunities){
  if(o.verification_status==='JSONLD_VERIFIED')card({kind:'verified',title:o.title,subtitle:`${o.company||'Organizzazione non dichiarata'} · ${place(o)}`,badges:[{text:o.sourceName||host(o.source_url),kind:'source'},{text:'Verificato',kind:'verified'},o.validity==='EXPIRED'?{text:'SCADUTO',kind:'warn'}:null,o.locationMatch==='CITY'?null:placeBadge(o)],facts:[{label:'Inserzionista',value:o.publisher_type&&o.publisher_type!=='UNKNOWN'?publisher(o):null},{label:'Contratto',value:contract(o.employmentType)},{label:'Pubblicato',value:nice(o.datePosted)},{label:'Valido fino a',value:o.validity==='EXPIRED'?`${nice(o.validThrough)} — SCADUTO`:o.validity==='CURRENT'?nice(o.validThrough):null}],notes:[`Verificato da dati strutturati dell'annuncio (JobPosting) · letto il ${nice(o.observed_at||o.discovered_at)||'data non disponibile'}${o.publisher_type==='UNKNOWN'||!o.publisher_type?' · inserzionista non verificato':''}${o.validity==='CURRENT'||o.validity==='EXPIRED'?'':' · validità non dichiarata'}`],url:o.source_url,label:'Apri annuncio originale →',key:'job:'+o.source_url});
  else if(o.verification_status==='LISTING_OBSERVED'&&o.sourceName==='Adzuna')card({kind:'observed',title:o.title,subtitle:`${o.company||'Azienda non dichiarata'} · ${place(o)}`,badges:[{text:'Adzuna',kind:'source'},o.locationMatch==='CITY'?null:placeBadge(o),o.publisher_type==='STAFFING_AGENCY'||o.publisher_type==='AGENCY'?{text:'Agenzia',kind:'warn'}:null],facts:[{label:'Pubblicato',value:nice(o.datePosted)},{label:'Contratto',value:contract(o.employmentType)},{label:'Retribuzione',value:o.salary&&(o.salary.min||o.salary.max)?`${o.salary.min?o.salary.min+' €':''}${o.salary.min&&o.salary.max?' – ':''}${o.salary.max?o.salary.max+' €':''} (dichiarata dall\'aggregatore)`:null}],notes:[`Annuncio da Adzuna (API ufficiale) · azienda e data come pubblicate dall\'aggregatore · ${publisher(o)} · disponibilità non verificata`],url:o.source_url,label:'Apri annuncio originale →',key:'job:'+o.source_url});
  else if(o.verification_status==='LISTING_OBSERVED')card({kind:'observed',title:o.title,subtitle:place(o),badges:[{text:'Subito',kind:'source'},o.locationMatch==='CITY'?null:placeBadge(o),o.publisher_type==='STAFFING_AGENCY'||o.publisher_type==='AGENCY'?{text:'Agenzia',kind:'warn'}:null],facts:[{label:'Osservato il',value:nice(o.observed_at||o.discovered_at)}],notes:[`Annuncio osservato su Subito · disponibilità non verificata · ${publisher(o)} · pagina annuncio non aperta`],url:o.source_url,label:'Apri annuncio originale →',key:'job:'+o.source_url});
  else card({kind:'imported',title:o.title,subtitle:`${o.occupation||r.occupation||''} · ${o.city||'Località non dichiarata'}${o.province?' ('+o.province+')':''}`,badges:[{text:o.sourceName||host(o.source_url),kind:'source'},r.status==='collected_results'?{text:'Osservazione importata',kind:'warn'}:null],facts:[{label:'Inserzionista',value:publisher(o)},{label:'Stato',value:`${o.status||'UNKNOWN'} · ${o.verification_status||'UNVERIFIED'}`},{label:'Raccolto',value:o.discovered_at||'non disponibile'}],notes:[`Disponibilità ${o.last_verified_at?'osservata il '+o.last_verified_at:'attuale non verificata'}${r.status==='collected_results'?' · osservazione importata, non live':''}`],url:o.source_url,label:'Apri annuncio originale →',key:'job:'+o.source_url});
 }
 for(const j of r.jobs||[])if(safe(j.url))card({kind:'observed',title:j.title,subtitle:`${j.city||''} · ${j.source||'Fonte originale'}`,badges:[{text:j.source||host(j.url),kind:'source'}],facts:[{label:'Inserzionista',value:'Inserzionista sconosciuto'},{label:'Rilevato',value:r.fetchedAt||'non disponibile'},{label:'Validità cache',value:r.expiresAt||'non disponibile'}],url:j.url,label:'Apri annuncio originale →',key:'job:'+j.url});
 for(const s of r.searchLinks||[])if(safe(s.url))card({kind:'search',title:s.title,subtitle:context,badges:[{text:host(s.url),kind:'source'},{text:'Ricerca',kind:'search'}],notes:['Ricerca / suggerimento di navigazione — non è un annuncio',`Link rilevato: ${s.discoveredAt||'data non disponibile'} · Inserzionista sconosciuto`],url:s.url,label:'Apri ricerca sulla fonte originale →',key:'search:'+s.url});
 for(const p of r.unavailablePages||[])if(safe(p.url))card({kind:'notice',title:p.title,subtitle:`${p.status} · ${p.reason}`,notes:[`Osservato: ${p.observedAt}`],url:p.url,label:'Apri pagina originale →',key:'status:'+p.url});
 }
}
function renderCards(){for(const n of $('#messages').querySelectorAll('.resultcard:not(.job-receipt)'))n.remove();for(const a of workspace.artifacts.filter(a=>a.conversation_id===current)){const c=elt('div',undefined,'resultcard');c.append(elt('strong',a.title),elt('p',`Bozza da controllare · Versione ${a.current_revision}`,'capabilities'));const b=elt('button','Apri risultato →');b.onclick=()=>openArtifact(a.id,true).catch(e=>notice(errorText(e)));c.append(b);$('#messages').append(c)}}
function setBusy(value){busy=value;for(const b of document.querySelectorAll('[data-action="sendhome"],[data-action="sendchat"]'))b.disabled=value;$('#cancel').hidden=!value;}
async function send(from){const input=$(from),text=input.value.trim();if(!text||busy)return;if(dirty){notice('Salva o annulla la modifica del risultato prima di continuare.');return}setBusy(true);let id=current;try{if(!id||from==='#homeinput'||from==='#dashinput'){const c=await api('/conversations',{title:text.slice(0,80)},'POST',crypto.randomUUID());id=c.id;current=id;sequence=0;task=null;run=null;mode('work');$('#messages').replaceChildren();$('#title').textContent=c.title;$('#crumb').textContent=c.title;}const e=++epoch;const body={baseSequence:sequence,text,...(task&&run?.status!=='completed'?{taskId:task}:{})};$('#activity').textContent='Invio in corso…';const result=await api(`/conversations/${id}/turns`,body,'POST',crypto.randomUUID());input.value='';document.querySelector('#dashinput')&&(document.querySelector('#dashinput').value='');task=result.taskId;run={...result,task_id:result.taskId};const list=await messages(id);if(e!==epoch)return;renderMessages(list);poll(result.id,e)}catch(err){setBusy(false);$('#activity').textContent=errorText(err);notice(errorText(err));await refresh().catch(()=>{});}}
async function poll(id,e){if(e!==epoch)return;setBusy(true);try{const r=await api('/runs/'+id);if(e!==epoch)return;run={...r,task_id:r.taskId};$('#runstatus').textContent=status(r.status);const events=await api(`/runs/${id}/events?limit=50`);if(e!==epoch)return;const kinds=events.items.map(x=>x.kind);$('#activity').textContent=r.error?errorText(Error(r.error)):kinds.includes('tool.succeeded')?'Risultato salvato. Sto preparando la risposta.':status(r.status);if(['queued','running'].includes(r.status)){timer=setTimeout(()=>poll(id,e),1200);return}await refresh();const list=await messages(current);if(e!==epoch)return;renderMessages(list);renderCards();renderJobReceipts(events.items);const a=workspace.artifacts.find(a=>a.conversation_id===current);if(a&&!dirty)await openArtifact(a.id,false);setBusy(false);$('#activity').textContent=r.error?errorText(Error(r.error)):r.status==='waiting_user'?'Puoi continuare rispondendo qui sotto.':'';}catch(err){setBusy(false);$('#activity').textContent=errorText(err);notice(errorText(err))}}
async function openArtifact(id,show=true,version){if(!canNavigate())return;const a=workspace.artifacts.find(a=>a.id===id);if(!a)return;const e=epoch,requestId=++artifactRequest;const r=await api(`/artifacts/${id}/revisions/${version||a.current_revision}`);if(e!==epoch||requestId!==artifactRequest||dirty)return;artifact=a;revision=r;dirty=false;$('#artifacttitle').textContent=a.title;$('#artifacttext').textContent=r.content.text;$('#revisionlabel').textContent=`Versione ${r.revision} · ${r.content.language}`;$('#saved').textContent='Versione salvata';$('#editor').value=r.content.text;$('#editor').hidden=true;$('#paper').hidden=false;$('#save').hidden=true;$('#download').hidden=false;$('#versions').hidden=true;if(show){document.body.dataset.studio='open';$('.studio').style.display='';$('.workspace').style.gridTemplateColumns='';}}
async function save(){if(!artifact||!revision||!dirty)return;const id=artifact.id,e=epoch,text=$('#editor').value,base=revision.revision;saving=true;$('#save').disabled=true;$('#editor').disabled=true;try{await api(`/artifacts/${id}/revisions`,{baseRevision:base,content:{text,language:revision.content.language}},'POST',crypto.randomUUID());saving=false;dirty=false;await refresh();if(e===epoch){await openArtifact(id,true);notice('Modifica salvata in una nuova versione.')}}catch(err){notice(errorText(err));$('#saved').textContent='Modifica non confermata. Il testo resta nell’editor.'}finally{saving=false;$('#save').disabled=false;$('#editor').disabled=false}}
$('#editor').addEventListener('input',()=>{dirty=true;$('#saved').textContent='Modifica non salvata'});$('#save').onclick=save;
$('#cancel').onclick=async()=>{if(run)try{await api('/runs/'+run.id+'/cancel',{},'POST',crypto.randomUUID());notice('Richiesta interrotta. I risultati già salvati restano disponibili.')}catch(e){notice(errorText(e))}};
$('#file').onchange=async()=>{const f=$('#file').files[0];if(!f)return;try{if(!f.name.endsWith('.txt')||f.size>16384)throw Error('file');if(!current){const c=await api('/conversations',{title:'Documento di testo'},'POST',crypto.randomUUID());current=c.id;await openConversation(c.id)}const id=current;const bytes=new Uint8Array(await f.arrayBuffer());const dataBase64=btoa(String.fromCharCode(...bytes));const name=f.name.replace(/[^A-Za-z0-9_-]/g,'_').slice(0,50)+'.txt';await api('/files',{conversationId:id,name,mime:'text/plain',dataBase64},'POST',crypto.randomUUID());notice('File salvato. Ora scrivi cosa vuoi farne.');}catch{notice('File non caricato. Sono accettati solo .txt UTF-8, massimo 16 KB.')}finally{$('#file').value=''}};
document.addEventListener('click',async e=>{const b=e.target.closest('button[data-action]');if(!b)return;try{switch(b.dataset.action){case'home':home();break;case'new':home(true);break;case'sendhome':await send('#homeinput');break;case'sendchat':await send('#chatinput');break;case'cv':$('#homeinput').value='Aiutami a preparare il mio curriculum. Fammi una domanda alla volta e salva una bozza senza inventare dati.';$('#homeinput').focus();break;case'explain':$('#homeinput').value='Vorrei capire un testo. Posso incollarlo qui?';$('#homeinput').focus();break;case'voice':notice('La conversazione vocale non è ancora disponibile. Puoi usare la dettatura della tastiera del telefono.');break;case'languages':notice('Puoi parlare con Nova in italiano, বাংলা o English. La lingua dell’interfaccia per ora è italiano.');break;case'upload':$('#file').click();break;case'back':if(!canNavigate())return;++artifactRequest;dirty=false;document.body.dataset.studio='';if(innerWidth>700){$('.studio').style.display='none';$('.workspace').style.gridTemplateColumns='1fr'}break;case'edit':++artifactRequest;if(!revision){notice('Apri prima un risultato.');break}if(run&&['queued','running'].includes(run.status)){notice('Attendi la fine del lavoro prima di modificare.');break}$('#editor').hidden=false;$('#paper').hidden=true;$('#save').hidden=false;$('#download').hidden=true;break;case'preview':++artifactRequest;if(revision&&canNavigate()){dirty=false;$('#editor').value=revision.content.text;$('#editor').hidden=true;$('#paper').hidden=false;$('#save').hidden=true;$('#download').hidden=false}break;case'versions':if(!artifact)break;$('#versions').replaceChildren();$('#versions').hidden=false;for(let v=artifact.current_revision;v>Math.max(0,artifact.current_revision-20);v--){const n=elt('button','v'+v);n.onclick=()=>openArtifact(artifact.id,true,v).catch(e=>notice(errorText(e)));$('#versions').append(n)}break;case'download':if(revision)download(revision.content.text,`nova-risultato-v${revision.revision}.txt`);break;case'print':if(revision&&!dirty)window.print();else notice('Salva la modifica prima di stampare.');break;case'results':home();$('#homerecent').replaceChildren();for(const a of workspace.artifacts){const n=elt('button',a.title+' →');n.onclick=async()=>{await openConversation(a.conversation_id);await openArtifact(a.id,true)};$('#homerecent').append(n)}break;case'exportdata':download(JSON.stringify(await api('/me/export'),null,2),'nova-i-miei-dati.json','application/json');break;case'logout':await request('/auth/logout',{});location.reload();break;case'providers':const settingsAction=window.openProviderSettings||openProviderSettings;settingsAction();break;}}catch(err){notice(errorText(err))}});
for(const id of ['#homeinput','#chatinput'])$(id).onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();send(id)}};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
async function start(){try{await refresh();$('#login').hidden=true;$('#shell').hidden=false;if(window.openDashboard)window.openDashboard();else home(true)}catch{$('#shell').hidden=true;$('#login').hidden=false;if(invite){$('#logintext').textContent='Hai un invito personale. Apri il tuo spazio per iniziare. Il link può essere usato una sola volta.';$('#enter').hidden=false;try{const {welcome}=await request('/auth/preview',{invite});if(welcome){$('#login').classList.add('personal-welcome');$('#login h1').textContent=welcome.title;let letter=$('#welcome-message');if(!letter){letter=document.createElement('p');letter.id='welcome-message';$('#logintext').before(letter)}letter.textContent=welcome.message;$('#logintext').textContent='Un invito personale, un nuovo inizio. Questo spazio è solo tuo.';$('#enter').textContent='Scopri NOVA';$('#login .capabilities').textContent='Anteprima privata · Il tuo invito resta valido fino al primo accesso.'}}catch{}$('#enter').onclick=async()=>{try{$('#enter').disabled=true;await request('/auth/exchange',{invite});await start()}catch(e){$('#logintext').textContent=errorText(e)}finally{$('#enter').disabled=false}}}}}
start();
