function renderJobReceipts(events){
 const box=$('#messages');for(const old of box.querySelectorAll('.job-receipt'))old.remove();const seen=new Set();
 const safe=raw=>{try{const u=new URL(raw);return u.protocol==='https:'&&!u.username&&!u.password&&!u.port&&!/^(?:localhost|\[|\d)/.test(u.hostname)&&!/\.(?:local|internal)$/.test(u.hostname)}catch{return false}};
 const day=v=>typeof v==='string'&&v.length>=10?v.slice(0,10):null;
 const host=u=>{try{return new URL(u).hostname.replace(/^www\./,'')}catch{return 'fonte originale'}};
 const nice=v=>{const d=day(v);if(!d)return null;const [y,m,g]=d.split('-');return `${g}/${m}/${y}`};
 const contract=v=>{if(!v)return null;const map={FULL_TIME:'Tempo pieno',PART_TIME:'Part time',TEMPORARY:'Temporaneo',CONTRACTOR:'Collaborazione',INTERN:'Stage',PER_DIEM:'A giornata',VOLUNTEER:'Volontariato',OTHER:'Altro'};return String(v).split(/[\s,]+/).filter(Boolean).map(x=>map[x.toUpperCase()]||x.toLowerCase().replace(/_/g,' ')).join(', ')};
 const card=o=>{if(seen.has(o.key))return;seen.add(o.key);
  const c=elt('article',undefined,'resultcard job-receipt job-card'+(o.kind?' job-card-'+o.kind:''));
  const head=elt('div',undefined,'job-card-head');const badges=elt('div',undefined,'job-badges');for(const b of o.badges||[])if(b&&b.text)badges.append(elt('span',b.text,'job-badge'+(b.kind?' job-badge-'+b.kind:'')));if(badges.childElementCount)head.append(badges);
  head.append(elt('h4',o.title||'Senza titolo','job-title'));if(o.subtitle)head.append(elt('p',o.subtitle,'job-subtitle'));c.append(head);
  const facts=elt('dl',undefined,'job-facts');for(const f of o.facts||[])if(f&&f.value){facts.append(elt('dt',f.label));facts.append(elt('dd',f.value))}if(facts.childElementCount)c.append(facts);
  for(const n of o.notes||[])if(n)c.append(elt('p',n,'job-note capabilities'));
  if(o.url&&safe(o.url)){const a=elt('a',o.label,'job-cta');a.href=o.url;a.target='_blank';a.rel='noopener noreferrer';c.append(a)}
  box.append(c)};
 for(const event of events){if(event.kind!=='tool.succeeded'||event.detail?.tool!=='jobs_search')continue;const r=event.detail.result;if(!r)continue;
 const req=r.requestedCity||r.city;const context=`${r.occupation||'Ruolo da chiarire'} · ${req||(r.remote?'Remoto':'Città da chiarire')}`;
 const opportunities=(r.opportunities||[]).filter(o=>safe(o.source_url));
 const explain=r.status!=='ok'||!opportunities.length;
 if(r.question||(explain&&(r.notice||r.sourceUnavailable)))card({kind:'notice',title:r.question||context,subtitle:r.question?context:null,notes:[explain?r.notice:null,explain&&r.sourceUnavailable?`Fonte non disponibile: ${r.sourceUnavailable.code||'motivo non dichiarato'}`:null],key:JSON.stringify([r.status,context,r.question])});
 if(opportunities.length){const rank=o=>o.locationMatch==='CITY'?0:o.locationMatch==='PROVINCE_OR_REGION'?1:o.locationMatch==='MISMATCH'?3:2;opportunities.sort((a,b)=>rank(a)-rank(b));
  const key='summary:'+context;if(!seen.has(key)){seen.add(key);const s=elt('div',undefined,'job-receipt job-summary');s.append(elt('strong',`${opportunities.length} ${opportunities.length===1?'annuncio trovato':'annunci trovati'}`),elt('span',context));const city=opportunities.filter(o=>o.locationMatch==='CITY').length;if(req&&city<opportunities.length)s.append(elt('span',`${city} a ${req} · ${opportunities.length-city} in provincia o altrove`));const off=r.subito?.offQuery;if(off)s.append(elt('span',`${off} non pertinenti esclusi`));box.append(s)}}
 const place=o=>{const loc=o.observedLocality||o.city||'Località non dichiarata';const prov=o.observedProvince||o.province||o.observedRegion;return `${loc}${prov?' ('+prov+')':''}`};
 const placeBadge=o=>o.locationMatch==='CITY'?{text:req||place(o),kind:'place'}:o.locationMatch==='PROVINCE_OR_REGION'?{text:`Provincia · non ${req||'il comune richiesto'}`,kind:'place'}:o.locationMatch==='MISMATCH'?{text:`Altra località · non ${req||'il comune richiesto'}`,kind:'warn'}:null;
 const publisher=o=>o.publisher_type==='DIRECT_EMPLOYER'?'Datore diretto con evidenza':o.publisher_type==='UNKNOWN'?'Inserzionista sconosciuto':o.publisher_type==='STAFFING_AGENCY'?'Agenzia per il lavoro':o.publisher_type==='AGENCY'?'Agenzia':o.publisher_type||'Inserzionista sconosciuto';
 for(const o of opportunities){
  if(o.verification_status==='JSONLD_VERIFIED')card({kind:'verified',title:o.title,subtitle:`${o.company||'Organizzazione non dichiarata'} · ${place(o)}`,badges:[{text:o.sourceName||host(o.source_url),kind:'source'},{text:'Verificato',kind:'verified'},o.validity==='EXPIRED'?{text:'SCADUTO',kind:'warn'}:null,o.locationMatch==='CITY'?null:placeBadge(o)],facts:[{label:'Inserzionista',value:o.publisher_type&&o.publisher_type!=='UNKNOWN'?publisher(o):null},{label:'Contratto',value:contract(o.employmentType)},{label:'Pubblicato',value:nice(o.datePosted)},{label:'Valido fino a',value:o.validity==='EXPIRED'?`${nice(o.validThrough)} — SCADUTO`:o.validity==='CURRENT'?nice(o.validThrough):null}],notes:[`Verificato da dati strutturati dell'annuncio (JobPosting) · letto il ${nice(o.observed_at||o.discovered_at)||'data non disponibile'}${o.publisher_type==='UNKNOWN'||!o.publisher_type?' · inserzionista non verificato':''}${o.validity==='CURRENT'||o.validity==='EXPIRED'?'':' · validità non dichiarata'}`],url:o.source_url,label:'Apri annuncio originale →',key:'job:'+o.source_url});
  else if(o.verification_status==='LISTING_OBSERVED')card({kind:'observed',title:o.title,subtitle:place(o),badges:[{text:'Subito',kind:'source'},o.locationMatch==='CITY'?null:placeBadge(o),o.publisher_type==='STAFFING_AGENCY'||o.publisher_type==='AGENCY'?{text:'Agenzia',kind:'warn'}:null],facts:[{label:'Osservato il',value:nice(o.observed_at||o.discovered_at)}],notes:[`Annuncio osservato su Subito · disponibilità non verificata · ${publisher(o)} · pagina annuncio non aperta`],url:o.source_url,label:'Apri annuncio originale →',key:'job:'+o.source_url});
  else card({kind:'imported',title:o.title,subtitle:`${o.occupation||r.occupation||''} · ${o.city||'Località non dichiarata'}${o.province?' ('+o.province+')':''}`,badges:[{text:o.sourceName||host(o.source_url),kind:'source'},r.status==='collected_results'?{text:'Osservazione importata',kind:'warn'}:null],facts:[{label:'Inserzionista',value:publisher(o)},{label:'Stato',value:`${o.status||'UNKNOWN'} · ${o.verification_status||'UNVERIFIED'}`},{label:'Raccolto',value:o.discovered_at||'non disponibile'}],notes:[`Disponibilità ${o.last_verified_at?'osservata il '+o.last_verified_at:'attuale non verificata'}${r.status==='collected_results'?' · osservazione importata, non live':''}`],url:o.source_url,label:'Apri annuncio originale →',key:'job:'+o.source_url});
 }
 for(const j of r.jobs||[])if(safe(j.url))card({kind:'observed',title:j.title,subtitle:`${j.city||''} · ${j.source||'Fonte originale'}`,badges:[{text:j.source||host(j.url),kind:'source'}],facts:[{label:'Inserzionista',value:'Inserzionista sconosciuto'},{label:'Rilevato',value:r.fetchedAt||'non disponibile'},{label:'Validità cache',value:r.expiresAt||'non disponibile'}],url:j.url,label:'Apri annuncio originale →',key:'job:'+j.url});
 for(const s of r.searchLinks||[])if(safe(s.url))card({kind:'search',title:s.title,subtitle:context,badges:[{text:host(s.url),kind:'source'},{text:'Ricerca',kind:'search'}],notes:['Ricerca / suggerimento di navigazione — non è un annuncio',`Link rilevato: ${s.discoveredAt||'data non disponibile'} · Inserzionista sconosciuto`],url:s.url,label:'Apri ricerca sulla fonte originale →',key:'search:'+s.url});
 for(const p of r.unavailablePages||[])if(safe(p.url))card({kind:'notice',title:p.title,subtitle:`${p.status} · ${p.reason}`,notes:[`Osservato: ${p.observedAt}`],url:p.url,label:'Apri pagina originale →',key:'status:'+p.url});
 }
}
