import {voiceInstructions} from './voice-policy.ts';
import type {FastifyInstance} from 'fastify';import type {Pool} from 'pg';import {authenticatedOwner,transaction,closed,uuid,fail} from './app.ts';import {extractPdf,renderPdf} from './documents.ts';import {azureToken,azureBase,searchWeb} from './azure-services.ts';
export function capabilityRoutes(app:FastifyInstance,pool:Pool){
 const authorize=(r:any)=>transaction(pool,c=>authenticatedOwner(c,r));
 const busy=new Map<string,number>();
 async function bounded<T>(r:any,work:()=>Promise<T>){const owner=await authorize(r);if((busy.get(owner)??0)>=2)fail(429,'capability_busy');busy.set(owner,(busy.get(owner)??0)+1);try{const result=await work();await authorize(r);return result}finally{const n=(busy.get(owner)??1)-1;if(n)busy.set(owner,n);else busy.delete(owner)}}
 app.post('/documents/extract',{bodyLimit:5700000,schema:{body:closed({dataBase64:{type:'string',maxLength:5600000}})}},async r=>bounded(r,async()=>{const b=Buffer.from((r.body as any).dataBase64,'base64');try{return await extractPdf(b)}catch{fail(422,'pdf_unreadable_or_over_limit')}}));
 app.get('/artifacts/:id/revisions/:revision/pdf',{schema:{params:closed({id:uuid,revision:{type:'string',pattern:'^[1-9][0-9]{0,8}$'}}),querystring:closed({template:{type:'string',enum:['classic','modern']}},[])}},async(r,reply)=>bounded(r,async()=>{const owner=await authorize(r),p=r.params as any;const row=(await pool.query('SELECT a.title,r.content FROM artifact_revisions r JOIN artifacts a ON a.id=r.artifact_id WHERE r.owner_id=$1 AND r.artifact_id=$2 AND r.revision=$3',[owner,p.id,Number(p.revision)])).rows[0];if(!row)fail(404,'not_found');const pdf=await renderPdf(row.title,row.content.text,(r.query as any).template??'classic');reply.type('application/pdf').header('content-disposition',`attachment; filename="nova-v${p.revision}.pdf"`);return pdf}));
 app.post('/research',{schema:{body:closed({query:{type:'string',minLength:3,maxLength:1000}})}},async r=>bounded(r,()=>searchWeb((r.body as any).query,AbortSignal.timeout(60000))));
 app.post('/voice/connect',{bodyLimit:40000,schema:{body:closed({sdp:{type:'string',minLength:10,maxLength:35000},language:{type:'string',enum:['auto','it','bn','en']}})}},async r=>bounded(r,async()=>{
  const signal=AbortSignal.timeout(30000),token=await azureToken(signal),body=r.body as any;
  const secretRes=await fetch(azureBase+'realtime/client_secrets',{method:'POST',redirect:'error',signal,headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({session:{type:'realtime',model:'gpt-realtime-2.1-mini',output_modalities:['audio'],instructions:voiceInstructions(body.language),audio:{output:{voice:'marin'},input:{turn_detection:{type:'server_vad',silence_duration_ms:900,prefix_padding_ms:300,create_response:true,interrupt_response:true}}}}})});
  if(!secretRes.ok)fail(503,'voice_unavailable');const secret=await secretRes.json() as any;if(!secret.value)fail(503,'voice_unavailable');await authorize(r);
  const response=await fetch(azureBase+'realtime/calls',{method:'POST',redirect:'error',signal,headers:{authorization:`Bearer ${secret.value}`,'content-type':'application/sdp'},body:body.sdp});if(!response.ok)fail(503,'voice_connection_failed');const sdp=await response.text();if(sdp.length>35000)fail(503,'voice_connection_failed');return {sdp,maxSeconds:180,model:'gpt-realtime-2.1-mini'};
 }));
}
