// Generates public/i18n.js from src/language.ts (single source of truth for interface strings).
// Run: npx tsx scripts/build-i18n.ts  — the i18n test fails if the generated file is stale.
import {writeFile} from 'node:fs/promises';import {UI_STRINGS,LANGUAGES} from '../src/language.ts';
export const render=()=>`'use strict';\n// GENERATED by scripts/build-i18n.ts from src/language.ts — do not edit by hand.\nconst NOVA_LANGUAGES=${JSON.stringify(LANGUAGES)};\nconst NOVA_STRINGS=${JSON.stringify(UI_STRINGS)};\n`;
if(process.argv[1]&&/build-i18n/.test(process.argv[1])){await writeFile(new URL('../public/i18n.js',import.meta.url),render());console.log('public/i18n.js written')}
