import pg from 'pg';import {readFile,mkdir,writeFile} from 'node:fs/promises';import {randomBytes,createHash} from 'node:crypto';import assert from 'node:assert/strict';
const root='/home/azureuser/.local/share/nova-community-trial',base=process.env.TRIAL_URL!;if(!/^https:\/\/[a-z-]+\.trycloudflare\.com$/.test(base))throw Error('origin');
const pool=new pg.Pool({host:'127.0.0.1',port:55439,user:'nova_trial',password:await readFile(root+'/db-secret','utf8'),database:'postgres'});const hash=(x:string)=>createHash('sha256').update(x).digest('hex');
try{assert.equal((await fetch(base)).status,200);assert.equal((await fetch(base+'/api/workspace')).status,401);assert.equal(await (await fetch(base+'/native.js')).text(),await readFile('staging/voice-files/public/native.js','utf8'));
const {bootstrap}=await import('../src/app.ts');const user=await bootstrap(pool);const test=randomBytes(32).toString('base64url');await pool.query("INSERT INTO web_invites VALUES($1,$2,clock_timestamp()+interval '5 minutes')",[hash(test),user.userId]);const headers={'content-type':'application/json','x-nova-request':'1',origin:base};const login=await fetch(base+'/auth/exchange',{method:'POST',headers,body:JSON.stringify({invite:test})});assert.equal(login.status,200);const cookie=login.headers.get('set-cookie')!.split(';')[0];const auth={...headers,cookie};assert.equal((await fetch(base+'/api/workspace',{headers:auth})).status,200);assert.equal((await fetch(base+'/auth/exchange',{method:'POST',headers,body:JSON.stringify({invite:test})})).status,401);
const cr=await fetch(base+'/api/conversations',{method:'POST',headers:{...auth,'idempotency-key':'release-conversation'},body:JSON.stringify({title:'Release verification'})});assert.equal(cr.status,201);const conversation=await cr.json();
const upload=await fetch(base+'/api/files/upload',{method:'POST',headers:{...auth,'idempotency-key':'release-file'},body:JSON.stringify({conversationId:conversation.id,name:'test.js',mime:'text/javascript',dataBase64:Buffer.from('console.log("Ricky test");').toString('base64')})});const uploaded=await upload.json();assert.equal(upload.status,201,JSON.stringify(uploaded));const downloaded=await fetch(base+'/api/files/'+uploaded.id+'/content',{headers:auth});assert.equal(downloaded.status,200);assert.equal(await downloaded.text(),'console.log("Ricky test");');console.log('Upload and exact download verified');
await fetch(base+'/auth/logout',{method:'POST',headers:auth,body:'{}'});assert.equal((await fetch(base+'/api/workspace',{headers:auth})).status,401);
const owner=JSON.parse(await readFile(root+'/ricky-invite-metadata.json','utf8')).owner;const invite=randomBytes(32).toString('base64url'),expires=process.env.SMOKE_INVITE_EXPIRES!;if(!expires||!(Date.parse(expires)>Date.now()))throw Error('SMOKE_INVITE_EXPIRES must be a future ISO timestamp');await pool.query('INSERT INTO web_invites VALUES($1,$2,$3)',[hash(invite),owner,expires]);const preview=await fetch(base+'/auth/preview',{method:'POST',headers,body:JSON.stringify({invite})});assert.equal(preview.status,200);assert.equal((await preview.json()).welcome.title,'Benvenuto, Ricky.');assert.equal((await pool.query('SELECT digest FROM web_invites WHERE digest=$1',[hash(invite)])).rowCount,1);
await mkdir('evidence/ricky-release-1',{recursive:true});await writeFile('evidence/ricky-release-1/public.json',JSON.stringify({base,publicAssetsVerified:true,loginReplayLogoutVerified:true,uploadStatus:upload.status,syntheticOwner:user.userId,recipientPreserved:true,expires},null,2));console.log('RICKY_LINK',base+'/#invite='+invite,'EXPIRES',expires);
}finally{await pool.end()}
