import {chromium} from 'playwright';import {readFile,writeFile,mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {database} from '../tests/helpers.ts';import {buildApp,migrate,bootstrap} from '../src/app.ts';import {AzureSpeechProvider} from '../src/voice-provider.ts';import {ManagedIdentityProvider} from '../src/managed-provider.ts';import {buildWeb,webDataRoutes} from '../src/web.ts';
declare const voiceChannel:RTCDataChannel;declare const voicePeer:RTCPeerConnection;declare const nativeVoiceId:string;declare function openConversation(id:string):Promise<void>;
declare global{interface Window{probeAudio:any;probeEvents:any[]}}
const report:any={boundary:'Isolated real PostgreSQL + native staged UI + actual managed chat and WebRTC synthetic microphone. No trial data.',errors:[]};const db=await database();await migrate(db.pool);const user=await bootstrap(db.pool),root=await mkdtemp(join(tmpdir(),'nova-actual-'));const app=buildApp(db.pool,{fileRoot:root,agent:{endpoint:'https://sadesheikh-2809-resource.openai.azure.com/openai/v1/chat/completions',model:'gpt-5.4-mini',provider:{complete:async(...args:Parameters<ManagedIdentityProvider['complete']>)=>{const result=await new ManagedIdentityProvider().complete(...args);(report.providerOutputs??=[]).push(result);return result}},voice:new AzureSpeechProvider(),timeoutMs:30000}});webDataRoutes(app,db.pool);await app.ready();const web=await buildWeb(app,db.pool,{nativeVoice:true});const browser=await chromium.launch({headless:true,args:['--no-sandbox','--autoplay-policy=no-user-gesture-required','--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream']});
try{const context=await browser.newContext({permissions:['microphone']});const page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));await page.route('https://nova.test/**',async route=>{const req=route.request(),url=new URL(req.url()),r=await web.inject({url:url.pathname+url.search,method:req.method() as any,headers:{...req.headers(),host:'nova.test',cookie:`__Host-nova=${user.token}`,origin:'https://nova.test'},...(req.postData()?{payload:req.postData()!}:{})});await route.fulfill({status:r.statusCode,headers:Object.fromEntries(Object.entries(r.headers).map(([k,v])=>[k,String(v)])),body:r.rawPayload})});
await page.goto('https://nova.test');await page.getByRole('button',{name:'Chat vocale',exact:true}).click();await page.getByRole('button',{name:'Avvia microfono',exact:true}).click();await page.waitForFunction(()=>{try{return voiceChannel?.readyState==='open'&&nativeVoiceId}catch{return false}},{},{timeout:45000});
const wav=(await readFile('evidence/voice-files-1/create-file.wav')).toString('base64');await page.evaluate(async b=>{const ctx=new AudioContext({sampleRate:48000}),dest=ctx.createMediaStreamDestination(),zero=ctx.createGain(),osc=ctx.createOscillator();zero.gain.value=0;osc.connect(zero).connect(dest);osc.start();await voicePeer.getSenders().find(x=>x.track?.kind==='audio')!.replaceTrack(dest.stream.getAudioTracks()[0]);const source=ctx.createBufferSource();source.buffer=await ctx.decodeAudioData(Uint8Array.from(atob(b),c=>c.charCodeAt(0)).buffer);source.connect(dest);source.start();window.probeAudio={ctx,osc,source};window.probeEvents=[];voiceChannel.addEventListener('message',e=>window.probeEvents.push(JSON.parse(e.data)))},wav);
let run:any;for(let n=0;n<180;n++){run=(await db.pool.query('SELECT id,status,error_code FROM agent_runs ORDER BY created_at DESC LIMIT 1')).rows[0];if(run&&!['running','queued'].includes(run.status))break;await new Promise(r=>setTimeout(r,500))}report.run=run;report.messages=(await db.pool.query('SELECT role,channel,provenance,text FROM messages ORDER BY sequence')).rows;report.receipts=(await db.pool.query('SELECT tool,result FROM agent_tool_receipts')).rows;
await page.waitForFunction(()=>window.probeEvents?.some(e=>e.type==='output_audio_buffer.stopped'),{},{timeout:30000});report.audio=await page.evaluate(async()=>({events:window.probeEvents.filter(e=>['error','response.output_audio_transcript.done','response.done'].includes(e.type)),stats:[...(await voicePeer.getStats()).values()].filter(x=>x.type==='inbound-rtp'&&x.kind==='audio').map(x=>({bytesReceived:x.bytesReceived,packetsReceived:x.packetsReceived}))}));
await page.getByRole('button',{name:'Termina sessione',exact:true}).click();await page.waitForTimeout(800);const receipt=report.receipts.find((r:any)=>r.tool==='create_file');if(!receipt)throw Error('actual_model_did_not_create_file');const file=await app.inject({url:receipt.result.download,headers:{authorization:`Bearer ${user.token}`}});report.download={status:file.statusCode,content:file.body,name:receipt.result.name};await page.reload();await page.waitForTimeout(400);const conversation=(await db.pool.query('SELECT id FROM conversations')).rows[0].id;await page.evaluate(id=>openConversation(id),conversation);await page.waitForTimeout(300);report.reopenedText=await page.locator('#messages').innerText();
const downloadEvent=page.waitForEvent('download');await page.locator('#download').click();const browserDownload=await downloadEvent;report.browserDownload={name:browserDownload.suggestedFilename(),content:await readFile((await browserDownload.path())!,'utf8')};
await page.locator('#chatinput').fill('Correct that same hello.js file to contain exactly console.log("Corrected Nova"); . Save the new revision; do not execute it.');await page.locator('[data-action="sendchat"]').click();for(let n=0;n<100;n++){const latest=(await db.pool.query('SELECT id,status,error_code FROM agent_runs ORDER BY created_at DESC LIMIT 1')).rows[0];if(latest.id!==run.id&&!['queued','running'].includes(latest.status)){report.correctionRun=latest;break}await new Promise(r=>setTimeout(r,500))}const corrected=await app.inject({url:`/artifacts/${receipt.result.id}/revisions/2/download`,headers:{authorization:`Bearer ${user.token}`}});report.correctionDownload={status:corrected.statusCode,content:corrected.body};report.success=corrected.statusCode===200&&corrected.body==='console.log("Corrected Nova");'&&report.browserDownload.content===file.body&&run?.status==='completed'&&file.statusCode===200&&report.messages.length===2&&report.audio.stats.some((x:any)=>x.bytesReceived>0);
}catch(e){report.error=(e as Error).message}finally{await browser.close();await web.close();await app.close();await db.close();await rm(root,{recursive:true,force:true});await writeFile('evidence/voice-files-1/actual-native-e2e-download-correction.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report))}
