import type {Pool,PoolClient} from 'pg';import type {FastifyInstance} from 'fastify';import {randomUUID} from 'node:crypto';
import {authenticatedOwner,transaction,closed,fail} from './app.ts';import {seal,unseal,foundryEndpoint,bedrockEndpoint,toBedrock,fromBedrock} from './provider-config.ts';import {azureToken,azureBase} from './azure-services.ts';import {parseCompletion} from './agent-provider.ts';
export class ProviderRegistry{
 constructor(private pool:Pool,private key:Buffer,private transport:typeof fetch=fetch){}
 async bind(c:PoolClient,owner:string){const p=(await c.query('SELECT provider,model FROM provider_preferences WHERE owner_id=$1',[owner])).rows[0]??{provider:'nova',model:'gpt-5.4-mini'};if(p.provider==='nova')return {...p,generation:null};const conn=(await c.query('SELECT generation FROM provider_connections WHERE owner_id=$1 AND provider=$2',[owner,p.provider])).rows[0];if(!conn)fail(409,'provider_not_connected');return {...p,generation:conn.generation}}
 async config(owner:string,binding:any){if(binding.provider==='nova')return {endpoint:azureBase,secret:undefined};const conn=(await this.pool.query('SELECT endpoint,secret_cipher,generation FROM provider_connections WHERE owner_id=$1 AND provider=$2',[owner,binding.provider])).rows[0];if(!conn||binding.generation&&conn.generation!==binding.generation)fail(409,'provider_connection_changed');return {endpoint:conn.endpoint,secret:unseal(this.key,owner,binding.provider,conn.secret_cipher)}}
 async readJson(url:string,options:any,max=1500000){const r=await this.transport(url,{...options,redirect:'error'});if(!r.ok){await r.body?.cancel();fail(409,r.status===401||r.status===403?'provider_access_denied':'provider_model_unavailable')}const body=await r.text();if(Buffer.byteLength(body)>max)fail(413,'provider_response_too_large');try{return JSON.parse(body)}catch{fail(409,'provider_malformed')}}
 async catalog(owner:string,provider:string){const cfg=await this.config(owner,{provider});const signal=AbortSignal.timeout(20000),headers:Record<string,string>={};if(provider==='nova')headers.authorization='Bearer '+await azureToken(signal);else if(provider==='foundry')headers['api-key']=cfg.secret!;else headers.authorization='Bearer '+cfg.secret;
 if(provider==='aws')return {items:[],manualModelId:true,message:'Inserisci il model ID o inference profile ID abilitato nella regione AWS. La chiave Bedrock non espone necessariamente il catalogo di gestione.',provider};
 let url=cfg.endpoint+'models',items:any[]=[];const seen=new Set<string>();for(let page=0;page<20;page++){const d=await this.readJson(url,{headers,signal});for(const m of d.data??[]){if(typeof m.id==='string'&&!seen.has(m.id)){seen.add(m.id);items.push({id:m.id,owner:m.owned_by??null,status:'catalogued_not_tested'})}}const next=d.nextLink??d.next;if(!next&&!d.has_more)return {items,total:items.length,provider,complete:true};if(typeof next!=='string')fail(409,'catalog_pagination_unsupported');const u=new URL(next,url);if(u.origin!==new URL(cfg.endpoint).origin||!u.pathname.startsWith(new URL(cfg.endpoint).pathname))fail(409,'unsafe_catalog_pagination');url=u.href;}fail(409,'catalog_too_large')}
 async complete(owner:string,binding:any,messages:any[],tools:any[],signal:AbortSignal){const cfg=await this.config(owner,binding);const headers:Record<string,string>={'content-type':'application/json'};let body:any,url:string;if(binding.provider==='aws'){headers.authorization='Bearer '+cfg.secret;url=cfg.endpoint+'model/'+encodeURIComponent(binding.model)+'/converse';body=toBedrock(messages,tools)}else{if(binding.provider==='nova')headers.authorization='Bearer '+await azureToken(signal);else headers['api-key']=cfg.secret!;url=cfg.endpoint+'chat/completions';body={model:binding.model,messages,tools,tool_choice:'auto',parallel_tool_calls:false,max_completion_tokens:2400}}const d=await this.readJson(url,{method:'POST',headers,body:JSON.stringify(body),signal},65536);return binding.provider==='aws'?fromBedrock(d):parseCompletion(d)}
 routes(app:FastifyInstance){const authorize=(r:any)=>transaction(this.pool,c=>authenticatedOwner(c,r));
 app.get('/providers',async r=>transaction(this.pool,async c=>{const owner=await authenticatedOwner(c,r);const connections=(await c.query('SELECT provider,endpoint,updated_at FROM provider_connections WHERE owner_id=$1',[owner])).rows;return {connections,selection:await this.bind(c,owner),keyStorage:'server-side AES-256-GCM, owner-bound; keys never returned',scope:'chat agent only; voice and web search use Nova managed service'}}));
 app.post('/providers/connect',{schema:{body:closed({provider:{type:'string',enum:['foundry','aws']},endpoint:{type:'string',maxLength:250},key:{type:'string',minLength:12,maxLength:6000}})}},async r=>{const b=r.body as any;let endpoint:string;try{endpoint=b.provider==='foundry'?foundryEndpoint(b.endpoint):bedrockEndpoint(b.endpoint)}catch{fail(400,'invalid_provider_endpoint')}return transaction(this.pool,async c=>{const owner=await authenticatedOwner(c,r);const secret=seal(this.key,owner,b.provider,b.key);await c.query('INSERT INTO provider_connections(owner_id,provider,endpoint,secret_cipher,generation) VALUES($1,$2,$3,$4,$5) ON CONFLICT(owner_id,provider) DO UPDATE SET endpoint=$3,secret_cipher=$4,generation=$5,updated_at=clock_timestamp()',[owner,b.provider,endpoint,secret,randomUUID()]);await authenticatedOwner(c,r);return {saved:true,provider:b.provider}})});
 app.post('/providers/disconnect',{schema:{body:closed({provider:{type:'string',enum:['foundry','aws']}})}},async r=>transaction(this.pool,async c=>{const owner=await authenticatedOwner(c,r);await c.query('DELETE FROM provider_connections WHERE owner_id=$1 AND provider=$2',[owner,(r.body as any).provider]);await c.query("DELETE FROM provider_preferences WHERE owner_id=$1 AND provider=$2",[owner,(r.body as any).provider]);return {disconnected:true}}));
 app.get('/providers/models',{schema:{querystring:closed({provider:{type:'string',enum:['nova','foundry','aws']}})}},async r=>{const owner=await authorize(r);const result=await this.catalog(owner,(r.query as any).provider);await authorize(r);return result});
 app.post('/providers/select',{schema:{body:closed({provider:{type:'string',enum:['nova','foundry','aws']},model:{type:'string',minLength:1,maxLength:300,pattern:'^[A-Za-z0-9._:/-]+$'}})}},async r=>transaction(this.pool,async c=>{const owner=await authenticatedOwner(c,r),b=r.body as any;if(b.provider!=='nova'&&!(await c.query('SELECT 1 FROM provider_connections WHERE owner_id=$1 AND provider=$2',[owner,b.provider])).rowCount)fail(409,'provider_not_connected');await c.query('INSERT INTO provider_preferences(owner_id,provider,model) VALUES($1,$2,$3) ON CONFLICT(owner_id) DO UPDATE SET provider=$2,model=$3,updated_at=clock_timestamp()',[owner,b.provider,b.model]);return {selected:true,provider:b.provider,model:b.model,appliesTo:'next turn; running requests remain pinned'}}));
 }
}
